### PR TITLE
Update for Fly 2.0

### LINKED ISSUE #1: does it work with v2?
hi, 
can this be upgraded to work with v2 ?

thanks in advanced.

### PR DESCRIPTION
**Pull request by lukeed**
Hi @iiegor!

My friend @wagerfield (and @devmondo) pointed out that this plugin hasn't been updated for the (semi-recent) release of Fly 2.0. So I went ahead & updated it. 😄 

#### Notable Changes

- Updated to Typescript 2.2
- Moved from `ts.transpile` to `ts.transpileModule` because of [its deprecation notice](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-a-single-file)
- Provide access to _all_ `TranspileOptions` (see  README)
- Reworked / Added a full suite of tests.

Also, a two-part question:
- a) Do you plan on maintaining this repo?
- b) Do you mind transferring this repo & NPM module to the Fly JS organization? We'll take good care of it 😺 

Closes #1

### CODE REVIEW

**Comment by iiegor** [comment]
Hey @lukeed, taking your time on this!

* a) I'm currently busy with other work so I have almost no time to maintain this. 
* b) Sure, I requested the transfer to @flyjs ;)

**Comment by lukeed** [comment]
Hi! Thank you!

You can go ahead & initiate the transfer to Fly or to me. I'll get it in there either way. 👍 

Also, please add me to the NPM package. That's quite important for future development 😉. My npm username is the same.

**Comment by iiegor** [comment]
@lukeed All done 😄 I transferred the repo to you

**Comment by lukeed** [comment]
Thanks so much! ❤️

**Pull request merged**
